import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import StyledComponentsRegistry from "@/app/registry";
import GlobalThemeWrapper from "@/app/GlobalThemeWrapper";
import Header from "@/components/Header/Header";
import {LayoutStayle} from "@/components/UI/LayoutStayle";


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <StyledComponentsRegistry>
            <GlobalThemeWrapper>
                <LayoutStayle>
                    <Header/>
                    <main>
                        {children}
                    </main>
                </LayoutStayle>
            </GlobalThemeWrapper>
        </StyledComponentsRegistry>
        </html>
    )
}
